### ISSUE TITLE
auto* overkill to build

### ISSUE THREAD

**Issue by benfleis** [ggreer/fsevents-tools#10]
I love what this code does, but it feels unneeded to have to install auto* for something that's mac specific.  Would you consider committing the autogen'd makefiles to the repo so that this can be avoided?

**Comment by ggreer** [comment]
If you don't want to install pkg-config and friends, feel free to download [a signed release tarball](http://geoff.greer.fm/fsevents/). They have the built configure scripts in them. I've added this info to the README.
