### ISSUE TITLE
Homebrew recipe

### ISSUE THREAD

**Issue by kach** [ggreer/fsevents-tools#14]
I would love to be able to install this via homebrew. Could you set it up as a brew formula? (If you need a third party to do it because of their policy, I'd be happy to submit it for you.)

**Comment by ggreer** [comment]
You're the second person to ask for this. (The first was [here](https://news.ycombinator.com/item?id=4562047).) Homebrew discourages people from submitting their own projects. I'd be very grateful if you submitted it. Let me know if I need to do anything.

**Comment by Hardmath123** [comment]
Cool. I have a busy workweek, but I'll try and get it done by this weekend.

Cheers!

**Comment by Hardmath123** [comment]
https://github.com/Homebrew/homebrew/pull/48159

Sorry it took a while. Hope it gets merged soon.

**Comment by avioli** [comment]
@Hardmath123: are you interested in actually re-submitting the formula, since it was not merged?

**Comment by Hardmath123** [comment]
I think it's on hold for lack of a correct test case.

**Comment by atdt** [comment]
Re-submitted with improved test case as  Homebrew/homebrew-core#4082

**Comment by atdt** [comment]
Merged. This can be closed now.
