### ISSUE TITLE
How to prevent getting .DS_Store file changes reportings?

### ISSUE THREAD

**Issue by dominik0711** [ggreer/fsevents-tools#15]
First of all, thanks for code sharing. I need to implement an own DirectoryWatcher with the following actions and with the corresponding filePaths:

  - **file added**
  - **file removed/deleted**
  - **file renamed** (from -> to)
  - **file movedTo** (from -> to)

So watching a directory I need to be informed when a file is removed/deleted, added or renamed incl. the full file path. Is it possible to use your implementation for that?
If so, how do I prevent reportings on "hidden" files like **.DS_Store**

Thanks in advance for your help!

**Comment by ggreer** [comment]
That would require using a newer version of the FSEvents API to monitor files as well as directories. Also, the logic to ignore files would be much larger than the current utility. It really sounds like this is not the right tool for what you want to do.
