### ISSUE TITLE
Separate scripts to another repo

### ISSUE THREAD

**Issue by JIghtuse** [ggreer/fsevents-tools#16]
I just tried to use notifyloop and autorsync on Fedora. Works fine if you just change `notifywait` to `inotifywait` in notifyloop.

So, why not to move these scripts to a new repo to get some kind of portability?

**Comment by JIghtuse** [comment]
Also, thanks for this project! I wrote something like notifyloop for myself just a few days ago.

**Comment by ggreer** [comment]
They're very simple scripts, but I have no intention of supporting them with inotify tools. The underlying APIs and command line tools are quite different. Incompatibilities are bound to pop up. Sorry.

**Comment by JIghtuse** [comment]
Ok, no problem. I'll add them to my tiny script collection then.
